### ISSUE TITLE
Duplicated messages on same host

### ISSUE THREAD

**Issue by mrkeuz** [kognise/arpchat#7]
Again! Really fun project! 🚀🚀🚀

If you run two instances on same host you receive duplicated messages (**ONLY** on receiver side)

![image](https://user-images.githubusercontent.com/6247921/159584156-97a1b807-f539-4e19-9ed3-6442bc998a8e.png)

### Env
`cargo +nightly build`
`cargo 1.60.0-nightly (95bb3c92b 2022-01-18)`
`Ubuntu 20.04.4 5.4.0-104-generic`

**Comment by kognise** [comment]
I can't seem to reproduce this, but I fixed it by deduplicating messages by id in 8e22e48 which should wipe away this whole class of issues. Gonna make a new release in a couple minutes.

**Comment by kognise** [comment]
https://github.com/kognise/arpchat/releases/tag/v0.3.0

**Comment by mrkeuz** [comment]
Confirm! Worked as expected on latest https://github.com/kognise/arpchat/commit/5174dafd115dd5c2ad34bc57591f6fcf05f17b8c 🚀🚀🚀

**Comment by mrkeuz** [comment]
@kognise hi again, I understand that it's just fun project, and I'm **NOT expected** to fix, REALLY.

Just FYI, found several issues:

- History not show messages that I sent from machine
- Sometimes users not detected but still receive messages as [unknown]. I've tried restart client - not help. Client that start FIRST not receive user list.
- At start, messages not deliver at all (couple messages or there is some timeout, I don't get it)

Notes:
- I run it on Linux → Linux (via Wi-Fi)
- In Wireshark messages are seems appearing . Can send `pcap` file to you, by email, if needed (just not want share mac addresses here). Just let me know.
  Here warm-up clients:
  
  ![image](https://user-images.githubusercontent.com/6247921/159632432-3d1f7ccd-db28-43c7-b1fd-7df326773c90.png)


![image](https://user-images.githubusercontent.com/6247921/159621928-5aa66dd2-0a7a-4be7-9637-7a1ef2355c5d.png)

**Comment by kognise** [comment]
hmm, that's weird! the implication is that some packets just aren't going through - i don't know if it's an issue of them being mutilated, or if they're just being dropped. could you open arpchat on only one device, reproduce one of the issues, and send me a pcap file from that device? if you'd prefer to email it, you can send to hi@kognise.dev.

if the problem is that the packets are being dropped i could try implementing some retry mechanism but it'll be a bit before i feel like doing something like that. in the meantime i am curious what the issue is :)

**Comment by mrkeuz** [comment]
What I found, on `lo` interface all ok. History working, all clients displayed correctly.

![image](https://user-images.githubusercontent.com/6247921/159643241-4cca18ce-6072-4fe6-b10b-f49da289226c.png)

BUT if you choose `wlan`/`eth0` (both clients runs locally) issue reproduced as described above. 

- Comparing `pcaps` (`lo` vs `wlan`/`eth0`) seems ARP packets drops/filtered on `wlan` by some reason ((( Also not see any criminal rules about in `iptables`, `ufw` or on router (not sure how arp packets sending in core).  Don't know where to dig after.
- `sudo` does not help (I thought maybe not enough some network permission) 
- `pcap` details sent to email
